### ISSUE TITLE
Suggestion: navigate forward/backward with volume keys

### ISSUE THREAD

**Issue by kingcit** [FengMoeTeam/NHentai-android#37]
It would be great to get a toggle to navigate forwards and backwards with tar volume keys.

**Comment by fython** [comment]
It's a good idea. In fact, I have made a plan to make this feature.

**Comment by NotCR** [comment]
@kingcit there you go buddy.It is now live with https://github.com/FengMoeTeam/NHentai-android/commit/d1e1f8ebdd878279c07ce0933f54c6ea4b64f58f, update your android studio project or wait a little bit for the apk release. 

 Volume Down for Next, Volume Up for previous

@fython want me to do a new release with APK with all the changes?

**Comment by fython** [comment]
@NotCR Good. You can simply write release logs in English.

**Comment by NotCR** [comment]
@fython I think it will be a problem if i upload the apk because it will be signed with another account.(Forcing them to uninstall and losing their favorites in the process) 

What about i make the release info and you add the apk and the source codes so they are not forced to uninstall, sounds good?

**Comment by fython** [comment]
Oh, I forgot to give you the key. Can you write down your email? @NotCR

**Comment by NotCR** [comment]
@notcr94@gmail.com
